---
title: "Run Lung Cancer Study"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

writeToCsv <- function(data, fileName) {
  colnames(data) <- SqlRender::camelCaseToSnakeCase(colnames(data))
  readr::write_csv(data, fileName)
}
```


```{r}
#' @export
# runStudy <- function(connectionDetails,
#                      connection  = NULL,
#                      cdmDatabaseSchema,
#                      tempEmulationSchema = NULL,
#                      oracleDatabaseSchema = NULL,
#                      cohortDatabaseSchema,
#                      writeDatabaseSchema,
#                      cohortTable = "cohort",
#                      cohortIdsToExcludeFromExecution = c(),
#                      cohortIdsToExcludeFromResultsExport = NULL,
#                      regimenIngredientsTable = regimenIngredientsTable,
#                      createRegimenStats = TRUE,
#                      createCategorizedRegimensTable = F,
#                      regimenStatsTable = 'default_rst',
#                      dropRegimenStatsTable = FALSE,
#                      exportFolder,
#                      databaseId,
#                      databaseName = databaseId,
#                      databaseDescription = "",
#                      gapBetweenTreatment = 120) {
```


# Connect to database

```{r}
connectionDetail <- Eunomia::getEunomiaConnectionDetails()
connection <- DatabaseConnector::connect(connectionDetails)
```


# Generate Study Cohorts

```{r}

cohortIdsConditionIndex <- getCohortsToCreate()$cohortId[4:6]
targetIdsTreatmentIndex <- getCohortsToCreate()$cohortId[1:3]

```


# Create Regimens

```{r}

```

# Generate Regimen Statistics

```{r}

createRegimenStats(
  connectionDetails = connectionDetails,
  cdmDatabaseSchema = cdmDatabaseSchema,
  writeDatabaseSchema = writeDatabaseSchema,
  cohortTable = cohortTable,
  regimenStatsTable = regimenStatsTable,
  regimenIngredientsTable = regimenIngredientsTable,
  gapBetweenTreatment = gapBetweenTreatment)

```

# Generate categorized regimens info

```{r}

categorizedRegimens <- createCateg %>% orizedRegimensTable(
  connectionDetails = connectionDetails,
  cohortDatabaseSchema = cohortDatabaseSchema,
  regimenStatsTable = regimenStatsTable,
  targetIds = targetIdsTreatmentIndex)

writeToCsv(categorizedRegimens, file.path(exportFolder, "categorizedRegimens_info.csv"))
```


# Generate survival info 

```{r}
ParallelLogger::logInfo("Generating survival info")

KMOutcomes <- getFeatures()
KMOutcomesIds <- KMOutcomes$cohortId[1]

SurvivalInfo <- generateSurvival(
  connection = connection,
  cohortDatabaseSchema = cohortDatabaseSchema,
  cohortTable = cohortTable,
  targetIds = targetIdsTreatmentIndex,
  outcomeId = KMOutcomesIds,
  databaseId = databaseId,
  packageName = getThisPackageName()
)

KMOutcomesIds <- KMOutcomes$cohortId[KMOutcomes$name %in% c("Death")]


writeToCsv(SurvivalInfo, file.path(
  exportFolder,
  "Survuval_info.csv"
))
```


# Generate treatment outcomes info 

```{r}
# time to treatment initiation
outcomesTI <- KMOutcomes$cohortId[KMOutcomes$name %in% c("Treatment initiation")]
timeToTI <- generateTimeToTreatmenInitiationStatistics(
  connection = connection,
  cohortDatabaseSchema = cohortDatabaseSchema,
  targetIds = cohortIdsConditionIndex,
  outcomeId = outcomesTI,
  cohortTable = cohortTable,
  databaseId = databaseId
)
writeToCsv(timeToTI, file.path(
  exportFolder,
  "timeToTI_info.csv"
))
```


```{r}
# time to next treatment
timeToNT <- generateKaplanMeierDescriptionTNT(
  connection = connection,
  cohortDatabaseSchema = cohortDatabaseSchema,
  regimenStatsTable = regimenStatsTable,
  targetIds = targetIdsTreatmentIndex,
  databaseId = databaseId
)

writeToCsv(timeToNT, file.path(
  exportFolder,
  "timeToNT_info.csv"
))
```


```{r}
# treatment free interval and time to treatment discontinuation
TFI <- generateKaplanMeierDescriptionTFI(
  connection = connection,
  cohortDatabaseSchema = cohortDatabaseSchema,
  regimenStatsTable = regimenStatsTable,
  targetIds = targetIdsTreatmentIndex,
  databaseId = databaseId
)

writeToCsv(TFI, file.path(
  exportFolder,
  "TFI_info.csv"
))
```


```{r}
TTD <- generateKaplanMeierDescriptionTTD(
  connection = connection,
  cohortDatabaseSchema = cohortDatabaseSchema,
  regimenStatsTable = regimenStatsTable,
  targetIds = targetIdsTreatmentIndex,
  databaseId = databaseId
)

writeToCsv(TTD, file.path(
  exportFolder,
  "TTD_info.csv"
))
```


```{r}
ParallelLogger::logInfo("Dropping RegimenStatsTable")
if(dropRegimenStatsTable){
  DatabaseConnector::renderTranslateExecuteSql(connection = connection,
                                               sql = "DROP TABLE IF EXISTS @writeDatabaseSchema.@regimenStatsTable",
                                               writeDatabaseSchema = writeDatabaseSchema,
                                               regimenStatsTable = regimenStatsTable
  )
}
```


# Generate metricsDistribution info 

```{r}
# prepare necessary tables
targetIdsFormatted <- targetIdsTreatmentIndex
pathToSql <- system.file("sql", "sql_server",
                         "distributions", "IQRComplementaryTables.sql",
                         package = getThisPackageName()
)

sql <- readChar(pathToSql, file.info(pathToSql)$size)

DatabaseConnector::renderTranslateExecuteSql(connection,
                                             sql = sql,
                                             cdmDatabaseSchema = cdmDatabaseSchema,
                                             cohortDatabaseSchema = cohortDatabaseSchema,
                                             cohortTable = cohortTable,
                                             targetIds = targetIdsFormatted
)

metricsDistribution <- data.frame()
DistribAnalyses <- c(
  "AgeAtIndex",
  "CharlsonAtIndex",
  "NeutrophilToLymphocyteRatioAtIndex",
  "PDLAtIndex",
  "PlateletToLymphocyteRatioAtIndex"
)
for (analysis in DistribAnalyses) {
  result <- getAtEventDistribution(
    connection = connection,
    cohortDatabaseSchema = cohortDatabaseSchema,
    cdmDatabaseSchema = cdmDatabaseSchema,
    cohortTable = cohortTable,
    targetIds = targetIdsTreatmentIndex,
    databaseId = databaseId,
    packageName = getThisPackageName(),
    analysisName = analysis
  )
  metricsDistribution <- rbind(metricsDistribution, result)
}




writeToCsv(metricsDistribution, file.path(
  exportFolder,
  "metrics_distribution__info.csv"
))
# drom temp tables
pathToSql <- system.file("sql",
                         "sql_server",
                         "distributions",
                         "RemoveComplementaryTables.sql",
                         package = getThisPackageName()
)
sql <- readChar(pathToSql, file.info(pathToSql)$size)
DatabaseConnector::renderTranslateExecuteSql(connection,
                                             sql = sql,
                                             cohortDatabaseSchema = cohortDatabaseSchema
)





```
